name: MYTELEBOT-CICD

on: push

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with: 
                fetch-depth: 0

            - name: Run test
              run: make test

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Build&Push
              env:
                APP: "mytelebot"
                REGISTRY: ghcr.io
                TARGETARCH: amd64
                TARGETOS: linux
              run: make image push

    cd: 
      name: CD
      needs: ci
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
          with: 
            fetch-depth: 0
        - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

        - uses: mikefarah/yq@master
          with:
            cmd: |
                 yq -i eval '.image.tag = strenv(VERSION)' helm/values.yaml
                 yq -i eval '.version = strenv(VERSION)' helm/Chart.yaml
            
        - run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -am "update version $VERSION"
            git push

